[package]
name = "ryba"
version = "0.1.0"
authors = ["Michael.Ilyin <milyin@gmail.com>"]

[dependencies]
serde="1.0"
serde_derive="1.0"
ryba-kit = { path = "../ryba-kit" }
rocket = { git = "https://github.com/SergioBenitez/Rocket" }
rocket_codegen = { git = "https://github.com/SergioBenitez/Rocket" }

[dependencies.rocket_contrib]
git = "https://github.com/SergioBenitez/Rocket"
features = ["tera_templates"]
